name: dependent-checker

executable:
  source-dirs: src
  main: Main

default-extensions:
- DataKinds
- GADTs
- KindSignatures
- LambdaCase
- StandaloneDeriving
- TupleSections

dependencies:
- base >= 4.7 && < 5
- dependent-base
- megaparsec
- mtl
- mmorph >= 1.2.0
